---
# tasks file for awsprovision
- ec2:
        region: ap-south-1
        key_name: kube
        instance_type: t2.micro
        image: ami-0bcf5425cdc1d8a85
        wait: yes
        group_id: sg-42489c25 
        count: 1
        vpc_subnet_id: subnet-a26069ca
        assign_public_ip: yes
        aws_access_key: AKIAWWVIBG52NURWNNFI
        aws_secret_key:  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


        
  register: x1
- blockinfile:
          path: /root/ip.txt
          marker: ""
          block: |
                  [master]
                  "{{item.public_ip}}"  ansible_user=ec2-user ansible_ssh_private_key_file=/root/kube.pem ansible_connection=ssh
  loop: "{{x1.instances}}"

- ec2:
        region: ap-south-1
        key_name: kube
        instance_type: t2.micro
        image: ami-0bcf5425cdc1d8a85
        wait: yes
        group_id: sg-42489c25
        count: 2
        vpc_subnet_id: subnet-a26069ca
        assign_public_ip: yes
        aws_access_key: AKIAWWVIBG52NURWNNFI
        aws_secret_key: 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

        
  register: x2
- blockinfile:
          path: /root/ip.txt
          marker: ""
          block: |
                  [slave]
                  "{{item.public_ip}}"  ansible_user=ec2-user ansible_ssh_private_key_file=/root/kube.pem ansible_connection=ssh
  loop: "{{x2.instances}}"

